### ISSUE TITLE
mod not working

### ISSUE THREAD

**Issue by Capei1** [comp500/ScreenshotToClipboard#10]
when i try to take a picture it says https://imgur.com/5mGGSVv
mod list https://imgur.com/EyjVGb2

**Comment by comp500** [comment]
Could you [post a log?](https://fabricmc.net/wiki/player:tutorials:logs_ml:windows)

**Comment by Capei1** [comment]
log?

**Comment by Capei1** [comment]
like mc log?

**Comment by Capei1** [comment]
[latest.log](https://github.com/comp500/ScreenshotToClipboard/files/5862164/latest.log)

**Comment by comp500** [comment]
Does it work without Optifine?

**Comment by Capei1** [comment]
i dont know

**Comment by comp500** [comment]
I can't reproduce this bug. Where did you get the mod jar from - it doesn't look like it has the same name as that of the official release on Curseforge? Try getting the mod from the correct page: https://www.curseforge.com/minecraft/mc-mods/screenshot-to-clipboard-fabric
