### ISSUE TITLE
[1.16.5] Crashes on MacOS

### ISSUE THREAD

**Issue by NielsPilgaard** [comp500/ScreenshotToClipboard#11]
Pressing F2 crashes the game.

Mod version: `1.15.1-1.0.5`

Crash report file:
https://gist.github.com/Rodg88/d34f29dc8bfd9dd43bc534162706ef36

Warning, 8.5MB log file ahead:
https://gist.githubusercontent.com/Rodg88/08fea2c46cd7e112f945208ee2377839/raw/f3eeeea08d30111474d588fccdfdf5c8b4bc4f62/screenshotcrash.log

Original report: https://github.com/NillerMedDild/Enigmatica6/issues/1400

**Comment by comp500** [comment]
Ah, looks like TextComponent internals have changed... that code was a bit of a hack anyway, I think I'll replace it with a mixin using forge-loom.

**Comment by comp500** [comment]
Resolved in 1.0.7 - releases now available on all platforms!
