### ISSUE TITLE
Doesn't copy fabrishot images

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [comp500/ScreenshotToClipboard#12]
Fabrishot allows you to take higher resolution screenshots, but screenshottoclipboard doesn't copy them. The default key for fabrishot screenshots are f9 (so you can separately take normal screenshots), but it can be set to f2 to override normal screenshots. Neither option is copied by screenshottoclipboard.

This is probably more a feature request than a bug report tbh.

**Comment by comp500** [comment]
That'd be cool, maybe you could request an API with some events for pre-save (raw ABGR data) and post-save (PNG file path) on the Fabrishot repo? Then it should be fairly easy to add support.

**Comment by DragonEggBedrockBreaking** [comment]
> That'd be cool, maybe you could request an API with some events for pre-save (raw ABGR data) and post-save (PNG file path) on the Fabrishot repo? Then it should be fairly easy to add support.

Idk much about programming, so it may be best if you do it. https://github.com/ramidzkh/fabrishot
