### ISSUE TITLE
Deprecated ModMenu Stuff

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [comp500/ScreenshotToClipboard#13]
This is put in logs: `[main/WARN]: WARNING! Mod screenshotclipboard is only using deprecated 'modmenu:clientsideOnly' custom value! This is no longer needed and will be removed in 1.18 snapshots.`

**Comment by DragonEggBedrockBreaking** [comment]
In the latest modmenu release for the 1.18 snapshots (21w38a is latest currently) of minecraft, the deprecated api has been removed. This is now more important to remain 1.18 compatible.

**Comment by comp500** [comment]
I already made this change in 2b97c5e698ec9afe2ef9c511c39ecb3940d149f8, but for some reason didn't push it!
