### ISSUE TITLE
Crash when you make a screen in 1.17

### ISSUE THREAD

**Issue by Francesco99d** [comp500/ScreenshotToClipboard#16]
I downloaded the latest version of the mod fabric for 1.17, it is loaded and recognized correctly with no errors.... But as soon as I make the screen with the F2 key the game crashes (disabling the mod everything works properly). I leave you the log of the crash: https://paste.ee/p/qJxcL

**Comment by comp500** [comment]
This is an incompatibility with Optifine. I can't really support Optifine when it patches the screenshot code like this - I can fix it temporarily, but it will change every version, so it really isn't worth the extra work to support.

**Comment by Francesco99d** [comment]
@comp500 I see, so what do you recommend I do? Do you know another mod or method compatible with Optifine? Thanks again for your reply and for creating the mod.... Good job ;)

**Comment by comp500** [comment]
I'd personally recommend not using Optifine (and [using alternatives](https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754)), as it causes many issues with other mods that are hard to debug and fix.

**Comment by Francesco99d** [comment]
Thanks for the tip.... I will take a look at it
