### ISSUE TITLE
Crashes when taking screenshot 1.17

### ISSUE THREAD

**Issue by schilzy** [comp500/ScreenshotToClipboard#17]
This crashes when activating. I love this mod can you please fix this. 

Minecraft version Fabric 1.17

**Comment by comp500** [comment]
I have no idea what issue you are having without a crash report or log, please send one!

**Comment by hollowstrawberry** [comment]
Hi, here's my crash report for this issue
[crash-2021-08-08_17.20.17-client.txt](https://github.com/comp500/ScreenshotToClipboard/files/6951476/crash-2021-08-08_17.20.17-client.txt)

**Comment by comp500** [comment]
Optifine is not supported with Screenshot to Clipboard. I can't really support Optifine when it patches the screenshot code like this - I can fix it temporarily, but it will change every version, so it really isn't worth the extra work to support.

**Comment by mrjesen** [comment]
> Optifine is not supported with Screenshot to Clipboard. I can't really support Optifine when it patches the screenshot code like this - I can fix it temporarily, but it will change every version, so it really isn't worth the extra work to support.

But,as usual,optfine is "almost neccessary" for every player.
