### ISSUE TITLE
Crash on F2

### ISSUE THREAD

**Issue by KruASe76** [comp500/ScreenshotToClipboard#18]
When Pressing F2, the game crashes (Fabric 1.17.1, mod version: screenshot_to_clipboard-fabric-1.15.21.17.1-1.0.7-fabric.jar from https://minecraft-inside.ru/mods/151523-screenshot-to-clipboard.html)
Maybe it is due to that I'm launching Minecraft with non-official launcher (TLauncher, latest version), but all the other fabric mods work correctly

Crash report here:
[crash-2021-11-02_08.56.12-client.txt](https://github.com/comp500/ScreenshotToClipboard/files/7458191/crash-2021-11-02_08.56.12-client.txt)

**Comment by comp500** [comment]
I don't support TLauncher or Optifine; the former has been known to cause many weird issues with mods, and the latter makes incompatible changes with Screenshot to Clipboard.
