### ISSUE TITLE
HeadlessException conflict with [SBM] Sheep Metal (depends on load order)

### ISSUE THREAD

**Issue by ProsperCraft** [comp500/ScreenshotToClipboard#2]
I press F2, it says it saved a screenshot, but doesn't go in the clipboard.

**Comment by comp500** [comment]
What version of Minecraft is this, and what operating system are you using?
What other mods are you using with this mod?

**Comment by ProsperCraft** [comment]
Windows 10

https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

Forge .50

**Comment by comp500** [comment]
Possible root cause discovered: A mod in the pack runs AWT libraries before Forge creates the mod classes

**Comment by comp500** [comment]
The bug seems to go away when [SBM] Sheep Metal is removed from the pack, however I can't reproduce it with just Screenshot to Clipboard and [SBM] Sheep Metal, and I can't find any code in that mod to cause a conflict.

**Comment by comp500** [comment]
Nevermind, I think I found the code that causes this - https://github.com/BuiltBrokenModding/SBM-SheepMetal/blob/master/src/main/java/com/builtbroken/sheepmetal/data/SheepTypes.java. I'll attempt a fix for this as soon as I can.

**Comment by comp500** [comment]
I've submitted an issue to help resolve this, see https://github.com/BuiltBrokenModding/SBM-SheepMetal/issues/2
