### ISSUE TITLE
Crash a few seconds after loading singleplayer world

### ISSUE THREAD

**Issue by ghost** [comp500/ScreenshotToClipboard#20]
Happens with the new 1.0.7 version of the mod not the 1.0.5 I was using previously

[crash-2021-11-11_12.39.15-client.txt](https://github.com/comp500/ScreenshotToClipboard/files/7522894/crash-2021-11-11_12.39.15-client.txt)

**Comment by comp500** [comment]
Optifine is not supported with Screenshot to Clipboard.
