### ISSUE TITLE
Crash when taking screenshots in 1.18.1 (crash report uploaded)

### ISSUE THREAD

**Issue by MercuryGryph** [comp500/ScreenshotToClipboard#22]
Crash when taking screenshots.

I tried to remove mods and find Optifabric and OptiFine is the reason.

But after Not Enough Crashes mod stop the crash, I can take screenshots and can find it in clipboard as it should be.

[crash-2022-01-29_16.28.46-client.txt](https://github.com/comp500/ScreenshotToClipboard/files/7963279/crash-2022-01-29_16.28.46-client.txt)

**Comment by MercuryGryph** [comment]
I know optifine is not supported with Screenshot to Clipboard.
But Not Enough Crashes mod can fix it. Hope you can find some way to fix it.

**Comment by comp500** [comment]
I don't think Not Enough Crashes can in any way fix the issue, only stop it from crashing your game entirely; since that crash still indicates that the ScreenshotRecorder class failed to load. Regardless, this is still an unsupported configuration - maintaining Optifine support would be a significant burden for me.

**Comment by MercuryGryph** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        I just found something strange.No matter what cause the crash, no crash will happen when taking screenshot anymore.Anyway, thanks for your reply.
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
    
        签名由网易邮箱大师定制
    
 

    On 1/29/2022 ***@***.***> wrote： 



I don't think Not Enough Crashes can in any way fix the issue, only stop it from crashing your game entirely; since that crash still indicates that the ScreenshotRecorder class failed to load. Regardless, this is still an unsupported configuration - maintaining Optifine support would be a significant burden for me.
