### ISSUE TITLE
Incompatibility with latest Fabrishot version (1.6.2)

### ISSUE THREAD

**Issue by manuelgrabowski** [comp500/ScreenshotToClipboard#25]
I first reported this in the Fabrishot repo: https://github.com/ramidzkh/fabrishot/issues/28

In 1.6.2 they made a breaking change, so the work done in https://github.com/comp500/ScreenshotToClipboard/issues/12 now results in a crash after taking a Fabrishot screenshot with this mod installed. Would be great to get compatibility back!

**Comment by comp500** [comment]
Fixed in https://github.com/comp500/ScreenshotToClipboard/commit/7480e7955beb4657b62432205cefabfd1950aedc :)
