### ISSUE TITLE
OptiFabric 1.15.2 and ScreenshotToClipboard causes a crash

### ISSUE THREAD

**Issue by liamdun** [comp500/ScreenshotToClipboard#7]
I can launch the game and play fine, but the moment i take a screenshot, Minecraft will say 'Saving game' then the game will close and I'll see the crash report on the launcher, optifabric and screenshottoclipboard worked great separately, even together actually, but the moment you press F2, the game will crash.

**Comment by comp500** [comment]
What versions of both mods do you have? I think I fixed this in the latest release, does it still happen when you update?

**Comment by liamdun** [comment]
optifabric-1.0.0-beta8
preview_OptiFine_1.15.2_HD_U_G1_pre19
ScreenshotToClipboardFabric-1.0.4

**Comment by comp500** [comment]
I already fixed this in Screenshot to Clipboard 1.0.5 - if it still doesn't work after updating reopen this issue :)
